pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build YourCalculatorApp.sln
  displayName: 'Build the solution'

- script: dotnet publish YourCalculatorApp.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the application'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial'
    appType: 'webApp'
    WebAppName: 'AZUREDEVOPS123'
    packageForLinux: '$(Build.ArtifactStagingDirectory)//*.zip'
    StartupCommand: 'dotnet YourCalculatorApp.dll'